var event = [
["AC", "Accounting"],
["CL", "Calculator"],
["CA", "Computer Apps"],
["CS", "Computer Sci"],
["CE", "Current Events"],
["GM", "General Math"],
["WR", "Journalism"],
["LC", "Literary Crit"],
["NS", "Number Sense"],
["SC", "Science"],
["SS", "Social Studies"],
["SP", "Spelling"]
];

var tres = [
["2021 AC", "1st Team Districts | 4th Team Regionals"],
["2021 CL", "1st Team Districts | 3rd Team Regionals"],
["2021 CS", "1st Team Districts | 3rd Team Regionals"],
["2021 CE", "1st Team Districts | 3rd Team Regionals"],
["2021 GM", "1st Team Districts | 2nd Team Regionals"],
["2021 LC", ""],
["2021 NS", "1st Team Districts | 2nd Team Regionals"],
["2021 SC", "1st Team Districts | 3rd Team Regionals"],
["2021 SS", "1st Team Districts | 5th Team Regionals"],
["2021 SP", "1st Team Districts | 1st Team Regionals | 1st Team State"],
["2022 AC", ""],
["2022 CL", "1st Team Districts | 2nd Team Regionals"],
["2022 CS", "1st Team Districts | 1st Team Regionals | 4th Team State"],
["2022 CE", "1st Team Districts | 1st Team Regionals | 3rd Team State"],
["2022 GM", "1st Team Districts | 1st Team Regionals | 3rd Team State"],
["2022 LC", "2nd Team Districts"],
["2022 NS", "1st Team Districts | 1st Team Regionals | 3rd Team State"],
["2022 SC", "1st Team Districts | 1st Team Regionals | 3rd Team State"],
["2022 SS", "1st Team Districts | 4th Team Regionals"],
["2022 SP", "1st Team Districts | 1st Team Regionals | 1st Team State"],
["2023 AC", ""],
["2023 CL", "1st Team Districts | 3rd Team Regionals"],
["2023 CS", "1st Team Districts | 1st Team Regionals | 1st Team State"],
["2023 CE", "2nd Team Districts | 1st Team Regionals | 2nd Team State"],
["2023 GM", "1st Team Districts | 1st Team Regionals | 3rd Team State"],
["2023 LC", "2nd Team Districts"],
["2023 NS", "1st Team Districts | 3rd Team Regionals"],
["2023 SC", "1st Team Districts | 1st Team Regionals | 1st Team State"],
["2023 SS", "6th Team Districts"],
["2023 SP", "1st Team Districts | 1st Team Regionals | 1st Team State"]
]

var res = [
["2021 AC", "Du Chen: | Allison Dwiggins: 4th Districts | Megha Reddy: 1st Districts | Christina Thapa: 5th Districts"],
["2021 CL", "Blake Maulsby: 5th Districts | Warith Rahman: 3rd Districts, 6th Regionals | Jenny Wei: 4th Districts | Anthony Xu: 2nd Districts"],
["2021 CA", "Giana Abraham: 3rd Districts | Pratham Patel: 2nd Districts | Warith Rahman: 1st Districts, 3rd Regionals"],
["2021 CS", "Mukul Agarwal: 6th Districts | Warith Rahman: 2nd Districts | Anthony Xu: 5th Districts | Eric Yang: 3rd Districts, 2nd Regionals"],
["2021 CE", "Mihir Gokhale: 1st Districts, 6th Regionals | Safwan Islam: 4th Districts | Dhanish Parimalakumar: | Sean Sudalaimani: 3rd Districts"],
["2021 GM", "Eshaan Doke: 1st Districts, 2nd Regionals | Warith Rahman: 1st Districts | Jenny Wei: 6th Districts | Hannah Xiao: 5th Districts"],
["2021 LC", "Byul Kim: "],
["2021 NS", "Abraham Cherian: 2nd Districts, 5th Regionals | Eshaan Doke: 3rd Districts | Warith Rahman: 1st Districts, 6th Regionals | Jenny Wei: 4th Districts"],
["2021 SC", "Amisha Baidya: | Eshaan Doke: 2nd Districts, 2nd Chem Districts, 2nd Phys Districts, 5th Regionals | Safwan Islam: 5th Districts | Jenny Wei: 1st Districts, 1st Chem Districts | Anthony Xu: 6th Districts | Eric Yang: 4th Districts, 1st Phys Districts"],
["2021 SS", "Amisha Baidya: | Mihir Gokhale: 1st Districts | Dhakshin Parimalakumar: | Sean Sudalaimani: 5th Districts"],
["2021 SP", "Daniel Bui: | Sanjana Kishore: 2nd Districts, 3rd Regionals | Blake Maulsby: 1st Districts, 2nd Regionals, 5th State | Warith Rahman: "],
["2021 WR", "Alessio Haro: 4th Headline Districts | Karoline Reeves: 1st Ready Districts, 2nd Ready Regionals, 4th Ready State"],
["2022 AC", "Christina Thapa: 4th Districts"],
["2022 CL", "Blake Maulsby: | Warith Rahman: 1st Districts, 2nd Regionals | Adithya Uppathil: 5th Districts | Anthony Xu: 2nd Districts | Jakob McPherson: "],
["2022 CA", "Andrew Bourinski: 2nd Districts | Pratham Patel: 6th Districts | Warith Rahman: 3rd Districts, 5th Regionals"],
["2022 CS", "Zafir Nasim: | Warith Rahman: 6th Districts | Anthony Xu: 3rd Districts, 4th Regionals | Eric Yang: 1st Districts, 2nd Regionals"],
["2022 CE", "Mihir Gokhale: 1st Districts, 1st Regionals, 1st State | Rishabh Gokhale: | Safwan Islam: | Veda Kutagula: 2nd Districts, 3rd Regionals"],
["2022 GM", "Blake Maulsby: 3rd Districts | Jakob McPherson: 4th Districts, 4th Regionals | Warith Rahman: 1st Districts, 1st Regionals | Anthony Xu: 2nd Districts, 3rd Regionals"],
["2022 LC", "Blake Maulsby: 6th Districts | Anaita Patil: 5th Districts | Tanika Patil: "],
["2022 NS", "Jakob McPherson: 1st Districts, 1st Regionals | Warith Rahman: 2nd Districts, 3rd Regionals | Anthony Xu: 3rd Districts, 5th Regionals"],
["2022 SC", "Rishi Gandikota: 5th Districts | Safwan Islam: | Veda Kutagula: | Warith Rahman: 4th Districts, 6th Regionals | Anthony Xu: 2nd Districts, 1st Chem Districts, 2nd Phys Districts, 2nd Regionals, 2nd Chem Regionals | Eric Yang: 3rd Districts, 1st Bio Districts, 1st Phys Districts, 3rd Regionals, 1st Phys Regionals, 2nd Phys State"],
["2022 SS", "Mihir Gokhale: 2nd Districts | Rishabh Gokhale: 5th Districts | Pratham Patel: 3rd Districts | Donovan Zhang: 1st Districts"],
["2022 SP", "Daniel Bui: 4th Districts, 3rd Regionals | Andrew Kim: 2nd Districts, 5th Regionals | Sanjana Kishore: 3rd Districts, 3rd Regionals | Blake Maulsby: 1st Districts, 1st Regionals, 1st State"],
["2022 WR", "Maelin Fan: 4th Ready Districts | Carl Hu: 3rd Feature Districts, 2nd News Districts, 2nd Feature Regionals, 3rd News Regionals, 6th Feature State, 6th News State | Karoline Reeves: 2nd Ready Districts, 6th Ready Regionals"],
["2023 AC", "Fayyad Hasnain: 3rd Districts | Andrew Wulur: 4th Districts"],
["2023 CL", "Warith Rahman: 1st Districts, 1st Regionals | Anthony Xu: 2nd Districts, 6th Regionals | Eric Yang: 3rd Districts | Blake Maulsby: 4th Districts | Jessie Wang: 5th Districts | Dina Spiegel: "],
["2023 CA", "Andrew Bourinski: 1st Districts"],
["2023 CS", "Anthony Xu: 1st Districts, 1st Regionals | Eric Yang: 2nd Districts, 1st Regionals, 2nd State | Zafir Nasim: 3rd Districts, 5th Regionals | Warith Rahman: 4th Districts"],
["2023 CE", "Veda Kutagula: 2nd Districts, 4th Regionals, 5th State | Drew Warninghoff: 4th Districts | Rishabh Gokhale: 3rd Regionals | Rishi Gandikota: 2nd Regionals | Pratham Patel: | Emman Khan: "],
["2023 GM", "Warith Rahman: 1st Districts, 1st Regionals | Eric Yang: 2nd Districts | Anthony Xu: 3rd Districts, 4th Regionals | Blake Maulsby: 4th Districts | Adithya Uppathil: 5th Districts | Arjun Chowdhry: "],
["2023 LC", "Sanjana Kishore: 1st Districts | Beckyn Endashaw: | Kate Vernon: | Ashlynn Street: "],
["2023 NS", "Warith Rahman: 1st Districts, 1st Regionals | Anthony Xu: 2nd Districts | Blake Maulsby: 3rd Districts | Adithya Uppathil: 4th Districts | Jessie Wang: 6th Districts | Daniel Bui: "],
["2023 SC", "Eric Yang: 1st Districts, 1st Chem Districts, 1st Phys Districts, 2nd Regionals, 1st Chem Regionals, 1st Phys Regionals, 4th State, 1st Phys State | Blake Maulsby: 2nd Districts, 1st Bio Districts, 4th Regionals, 1st Bio Regionals, 1st Bio State | Anthony Xu: 3rd Districts, 2nd Chem Districts, 2nd Phys Districts, 3rd Regionals, 2nd Phys Regionals, 5th State, 2nd Phys State | Warith Rahman: 4th Districts, 2nd Chem Districts | Rishi Gandikota: 5th Districts, 2nd Chem Districts | Drew Warninghoff: "],
["2023 SS", "Arjun Chowdhry: | Pratham Patel: | Rishabh Gokhale: "],
["2023 SP", "Andrew Kim: 2nd Districts, 4th State | Daniel Bui: 3rd Districts | Sanjana Kishore: 4th Districts, 4th Regionals | Jocelyn Parks: 6th Districts | Herish Tripathi: "],
["2023 WR", "Eryn Rodriguez: 6th Ready Districts | Carl Hu: 2nd Feature Districts, 1st News Districts, 6th News Regionals | Karoline Reeves: 3rd Ready Districts, 1st Ready Regionals, 1st Ready State | Joshua Moro: 5th Feature Districts"],
]